# Generated by Django 3.1.7 on 2021-07-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivek', '0010_auto_20210711_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(default=True),
        ),
    ]
