# Generated by Django 3.1.7 on 2021-07-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivek', '0013_auto_20210711_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
